version: "3.8"

services:
  app: 
    container_name: docker-node-mysql
    restart: always
    command: node app.js
    build: .
    ports:
      - '3000:3000'

    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      #- MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes: 
      - .db-data:/var/lib/mysql
 
    
    